# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Server
source:           docs
destination:      _gh_pages
host:             0.0.0.0
port:             9002
url:              https://todc.github.io/todc-bootstrap
baseurl:          /docs/3.4
encoding:         UTF-8

gems:
  - jekyll-sitemap

# Custom vars
current_version:  3.4.0-3.4.0
docs_version:     3.4
repo:             https://github.com/todc/todc-bootstrap

download:
  source:         https://github.com/todc/todc-bootstrap/archive/v3.4.0-3.4.0.zip
  dist:           https://github.com/todc/todc-bootstrap/releases/download/v3.4.0-3.4.0/todc-bootstrap-3.4.0-3.4.0-dist.zip

bs:
  current_version:  3.4.0
  repo:             https://github.com/twbs/bootstrap
  download:
    source:         https://github.com/twbs/bootstrap/archive/v3.4.0.zip
    dist:           https://github.com/twbs/bootstrap/releases/download/v3.4.0/bootstrap-3.4.0-dist.zip
    sass:           https://github.com/twbs/bootstrap-sass/archive/v3.4.0.tar.gz
  blog:             https://blog.getbootstrap.com
  expo:             https://expo.getbootstrap.com
  themes:           https://themes.getbootstrap.com
  docs:             https://getbootstrap.com

sass_repo:        https://github.com/twbs/bootstrap-sass

cdn:
  # See https://www.srihash.org for info on how to generate the hashes
  css:            https://stackpath.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css
  css_hash:       "sha384-PmY9l28YgO4JwMKbTvgaS7XNZJ30MK9FAZjjzXtlqyZCqBY6X6bXIkM++IkyinN+"
  css_theme:      https://stackpath.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap-theme.min.css
  css_theme_hash: "sha384-jzngWsPS6op3fgRCDTESqrEJwRKck+CILhJVO5VvaAZCq8JYf8HsR/HPpBOOPZfR"
  js:             https://stackpath.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js
  js_hash:        "sha384-vhJnz1OVIdLktyixHY4Uk3OHEwdQqPppqYR8+5mjsauETgLOcEynD9oPHhhz18Nw"
